name: scratch
version: "0"

dependencies:
  - base >= 4.7 && < 5
  - Chart >= 1.8
  - Chart-diagrams >= 1.8
  - colour >= 2.3
  - containers
  - diagrams-lib >= 1.4
  - diagrams-svg >= 1.4
  - lens >= 4.15
  - recursion-schemes
  - free
  - comonad

library:
  exposed-modules:
    - Base16
    - LazyPattern
    - Synthetic
